### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Hombre2014**
Final submit for a review. The requirements for the project are below:

This is the back-end repo. The link to the front-end repo is [here](https://github.com/Hombre2014/book-a-class-frontend)

The PR for the front-end is [here](https://github.com/Hombre2014/book-a-class-frontend/pull/13)

#### Basics
- You should follow the layout of [the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). You should change only the titles, descriptions, and photos - in order to create a website about something other than motorcycles.
- Select a theme for your website - is it going to be a website for booking doctor appointments, booking online classes, or something else?

#### Features

**Core features - for teams of each size**
- The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).
- In the navigation panel, the user can see links to:
    - Motorcycles/doctors/classes/items that you selected as a theme.
    - "Reserve" form.
    - "My reservations".
    - "Add motorcycle/doctor/class/item that you selected as a theme" (if you are in a group of 4 people the link is visible to everybody).
    - "Delete motorcycle/doctor/class/item that you selected as a theme" (if you are in a group of 4 people the link is visible to everybody).
- On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).
main page

- When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).
    - In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).
Details page

- When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.

- Make the app responsive, creating both mobile and desktop versions.

**If your team has more than 2 members these are the required features; otherwise, they are additional features**
- When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with title and "Delete" button.
    - When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.
- To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
    - Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.
    - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.
Reserve and appointment
- When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).
- Add full documentation for your API.

**If your team has 5 members these are the required features; otherwise, they are additional features**

- Implement proper user authentication from the front-end to the server.
- Make sure that the "Add item" and "Delete item" links are accessible only by users who are admins.

#### Technical set up
- Set up the repository/repositories on GitHub and use Gitflow.
- You should use Postgres as your database
- Use Rails to create backend API.
- Use React & Redux to create frontend UI.
- You can choose if you want to set up your project as two separate apps or as one.
- The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
Hi @Hombre2014, @imubarak234, @KayLemba,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

- [ ] You still need to send the front-end for review, so please open a PR there and request another review.
- [ ] There are some commented code in your files, especially the ones related to authenticating the user, so I suggest that you remove all unnecessary code.
- [ ] It would be nice if you build tests for your back-end app.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Hombre2014** [comment]
Thanks for the fast review. We are still working on it.

**Comment by Hombre2014** [comment]
Some of your suggestions have been implemented. We are only three people and we really have not time for doing some testing.

**Review by mcrd25 — COMMENTED** [review]
Hi @Hombre2014 @MuriloRoque @imubarak234 @KayLemba , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
- I noticed you have already merged but please, tests were a requirement for the project. Next time, don't forget tests, they are extremely important.
- Maybe consider adding Swagger documentation with `rswag` app. It'd make your API more professional. I've yet to come across an API in my experience at Deloitte that does not have Swagger or similar documentation


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Hombre2014** [comment]
Thanks for your review. I do not think tests were required by the project. I do not see them, so please, correct me if I am wrong. For the documentation, I agree, but we are only three people and mainly two (in reality) we had no time to implement the documentation on time. We concentrated on getting the project working and we succeed.

**Comment by mcrd25** [comment]
@Hombre2014 

You're absolutely right, it's not on your official guidelines. It was on mine! So Yes, you are totally right.

Hope review was helpful anyway. consider maybe doing them later on. When you do remember for every negative scenario cover a postive one. Don't just test for when you expect something to fail but when you expect it to be successful (throw message etc.) For instance if something is controlled by length and cannot be less than 2 characters. Test when it's less than and when it's >=2. I'd even say do edge case so <, =, >. That ensure you know it works. Don't ever take for granted something is successful. Of course I don't mean menial things but apply this to core parts of application. What you expect when you receive something unexpected or expected and how you expect your application to handle it. I'm just giving this based on my experience reviewing code - Hopefully it'd help you in future. In Real World. No tests can be very very risky and cost time and money.

If you liked my review, feel free to connect on LinkedIn and leave a skill endorsement: https://www.linkedin.com/in/mayadouglas/

You are also free to follow me on GitHub

**Pull request merged**
